version: "3.8"
services:
  nginx:
    container_name: nginx-pgi
    image: nginx:1.25.3
    volumes:
      - type: bind
        source: ./volume/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    expose:
      - 80
      - 8000
    ports:
      - 80:80
    networks:
      - pgi_bridge
    # depends_on:
    #   - nextjs

  nextjs:
    container_name: nextjs-pgi
    image: sashkashishka/pgi-front
    volumes:
      - type: bind
        source: ./volume/nextjs
        target: /usr/app/logs
        read_only: false
    env_file:
      - "./config/envs/.env.nextjs"
    networks:
      - pgi_bridge
    depends_on:
      - strapi

  strapi:
    container_name: strapi-pgi
    image: sashkashishka/pgi-strapi
    volumes:
      - type: bind
        source: ./volume/strapi
        target: /opt/app/public
        read_only: false
    env_file:
      - "./config/envs/.env.strapi"
    networks:
      - pgi_bridge
    depends_on:
      - db

  db:
    container_name: mysql-pgi
    platform: linux/amd64
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./volume/myslq
        target: /var/lib/mysql
        read_only: false
      - type: bind
        source: ./config/myslq
        target: /docker-entrypoint-initdb.d
        read_only: true
    env_file:
      - "./config/envs/.env.strapi"
    networks:
      - pgi_bridge

networks:
  pgi_bridge:
