name: Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  front:
    name: Build front image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push front image
      uses: docker/build-push-action@v5
      with:
        context: ./front
        file: ./front/Dockerfile
        push: true
        tags: sashkashishka/pgi-front:${{ github.sha }}


  strapi:
    name: Build strapi image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push strapi image
      uses: docker/build-push-action@v5
      with:
        context: ./strapi
        file: ./strapi/Dockerfile
        push: true
        tags: sashkashishka/pgi-strapi:${{ github.sha }}


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [front, strapi]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy deploy dir
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "deploy/docker-compose.yaml,deploy/scripts/,deploy/config/"
        target: ~/${{ secrets.DIR }}

    - name: Pull images
      uses: appleboy/ssh-action@v1.0.1
      env:
        FRONT_VERSION: ${{ github.sha }}
        STRAPI_VERSION: ${{ github.sha }}
        DIR: ${{ secrets.DIR }}
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: FRONT_VERSION,STRAPI_VERSION,DIR
        script: |
          bash ~/${{ secrets.DIR }}/deploy/scripts/pull-images.sh

    - name: Start containers
      uses: appleboy/ssh-action@v1.0.1
      env:
        FRONT_VERSION: ${{ github.sha }}
        STRAPI_VERSION: ${{ github.sha }}
        DIR: ${{ secrets.DIR }}
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: FRONT_VERSION,STRAPI_VERSION,DIR
        script: |
          bash ~/${{ secrets.DIR }}/deploy/scripts/start-images.sh
