name: Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get short sha
      uses: benjlevesque/short-sha@v2.2
      id: short-sha
      with:
        length: 6

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_TOKEN }}

    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@v4
    #   with:
    #     images: |
    #       sashkashishka/pgi-front
    #       sashkashishka/pgi-strapi

    # - name: Build and push front image
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: ./front
    #     file: ./front/Dockerfile
    #     push: true
    #     tags: sashkashishka/pgi-front:${{ steps.short-sha.outputs.sha }}

    # - name: Build and push strapi image
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: ./strapi
    #     file: ./strapi/Dockerfile
    #     push: true
    #     tags: sashkashishka/pgi-strapi:${{ steps.short-sha.outputs.sha }}


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      working-directory: config/terraform
      run: terraform init

    # - name: Terraform Format
    #   working-directory: config/terraform
    #   run: terraform fmt -check

    - name: Terraform Apply
      working-directory: config/terraform
      run: |
        terraform apply -auto-approve -input=false \
        -var mysql_root_password=${{ secrets.MYSQL_ROOT_PASSWORD }} \
        -var db_name=${{ secrets.DB_NAME }} \
        -var db_user=${{ secrets.DB_USER }} \
        -var db_password=${{ secrets.DB_PASSWORD}} \
        -var nomad_token=${{ secrets.NOMAD_TOKEN }} \
        -var nomad_addr=${{ secrets.NOMAD_ADDR }} \
        -var jwt_secret=${{ secrets.JWT_SECRET }} \
        -var node_env=production \
        -var docker_username=${{ secrets.DOCKER_USERNAME }} \
        -var strapi_version=5636de \
        -var front_version=5636de \
        -var strapi_app_keys=${{ secrets.STRAPI_APP_KEYS }} \
        -var strapi_api_token_salt=${{ secrets.STRAPI_API_TOKEN_SALT }} \
        -var strapi_admin_jwt_secret=${{ secrets.STRAPI_ADMIN_JWT_SECRET }} \
        -var strapi_transfer_token_salt=${{ secrets.STRAPI_TRANSFER_TOKEN_SALT }} \
        -var jwt_secret=${{ secrets.JWT_SECRET }} \
        -var hostname=${{ secrets.HOSTNAME }}
